@OrderManagement.Api_HostAddress = http://localhost:5053

POST {{OrderManagement.Api_HostAddress}}/AddOrder/
Content-Type: application/json

{
  "orderName":"Some Order"
}

###

GET {{OrderManagement.Api_HostAddress}}/Orders/
Accept: application/json
